[project]
name = "ebooktools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "einops>=0.8.1",
    "indralib>=0.2.5",
    "lxml>=5.3.1",
    "lxml-stubs>=0.5.1",
    "numpy>=2.2.3",
    "ollama>=0.4.7",
    "pillow>=11.1.0",
    "pycryptodome>=3.21.0",
    "pymupdf>=1.25.3",
    "pypdf>=5.3.0",
    "pysdl2>=0.9.17",
    "pysdl2-dll>=2.30.10",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "sentence-transformers>=3.4.1",
    "torch>=2.6.0",
]
